-- Deep Roots IX private team roster storage
-- Run once in Supabase SQL Editor.

create table if not exists public.team_rosters (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  team_size integer not null check (team_size between 1 and 6),
  members jsonb not null,
  created_at timestamptz not null default now(),
  unique (team_id),
  constraint team_rosters_members_array check (
    jsonb_typeof(members) = 'array'
    and jsonb_array_length(members) = team_size
  )
);

alter table public.team_rosters enable row level security;

-- Public visitors may submit a roster, but they cannot read any roster data.
drop policy if exists "Public can submit team rosters" on public.team_rosters;
create policy "Public can submit team rosters"
on public.team_rosters
for insert
to anon
with check (
  team_size between 1 and 6
  and jsonb_typeof(members) = 'array'
  and jsonb_array_length(members) = team_size
);

-- Signed-in administrators can privately view and manage roster data.
drop policy if exists "Admins can view team rosters" on public.team_rosters;
create policy "Admins can view team rosters"
on public.team_rosters
for select
to authenticated
using (true);

drop policy if exists "Admins can add team rosters" on public.team_rosters;
create policy "Admins can add team rosters"
on public.team_rosters
for insert
to authenticated
with check (true);

drop policy if exists "Admins can update team rosters" on public.team_rosters;
create policy "Admins can update team rosters"
on public.team_rosters
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Admins can delete team rosters" on public.team_rosters;
create policy "Admins can delete team rosters"
on public.team_rosters
for delete
to authenticated
using (true);
